package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AirlineCompany generated by hbm2java
 */
public class AirlineCompany  implements java.io.Serializable {


     private Integer idairlineCompany;
     private String name;
     private String address;
     private String country;
     private String webSite;
     private String email;
     private Set<Airplane> airplanes = new HashSet<Airplane>(0);

    public AirlineCompany() {
    }

	
    public AirlineCompany(String name, String address, String country, String webSite, String email) {
        this.name = name;
        this.address = address;
        this.country = country;
        this.webSite = webSite;
        this.email = email;
    }
    public AirlineCompany(String name, String address, String country, String webSite, String email, Set<Airplane> airplanes) {
       this.name = name;
       this.address = address;
       this.country = country;
       this.webSite = webSite;
       this.email = email;
       this.airplanes = airplanes;
    }
   
    public Integer getIdairlineCompany() {
        return this.idairlineCompany;
    }
    
    public void setIdairlineCompany(Integer idairlineCompany) {
        this.idairlineCompany = idairlineCompany;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Airplane> getAirplanes() {
        return this.airplanes;
    }
    
    public void setAirplanes(Set<Airplane> airplanes) {
        this.airplanes = airplanes;
    }




}


