package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AirplaneMaker generated by hbm2java
 */
public class AirplaneMaker  implements java.io.Serializable {


     private Integer idairplaneMaker;
     private String name;
     private String city;
     private String country;
     private Set<AirplaneTypes> airplaneTypeses = new HashSet<AirplaneTypes>(0);

    public AirplaneMaker() {
    }

	
    public AirplaneMaker(String name, String city, String country) {
        this.name = name;
        this.city = city;
        this.country = country;
    }
    public AirplaneMaker(String name, String city, String country, Set<AirplaneTypes> airplaneTypeses) {
       this.name = name;
       this.city = city;
       this.country = country;
       this.airplaneTypeses = airplaneTypeses;
    }
   
    public Integer getIdairplaneMaker() {
        return this.idairplaneMaker;
    }
    
    public void setIdairplaneMaker(Integer idairplaneMaker) {
        this.idairplaneMaker = idairplaneMaker;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<AirplaneTypes> getAirplaneTypeses() {
        return this.airplaneTypeses;
    }
    
    public void setAirplaneTypeses(Set<AirplaneTypes> airplaneTypeses) {
        this.airplaneTypeses = airplaneTypeses;
    }




}


