package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AirplaneLicence generated by hbm2java
 */
public class AirplaneLicence  implements java.io.Serializable {


     private Integer idairplaneLicence;
     private AirplaneTypes airplaneTypes;
     private String licence;
     private Set<PilotLicence> pilotLicences = new HashSet<PilotLicence>(0);

    public AirplaneLicence() {
    }

	
    public AirplaneLicence(AirplaneTypes airplaneTypes, String licence) {
        this.airplaneTypes = airplaneTypes;
        this.licence = licence;
    }
    public AirplaneLicence(AirplaneTypes airplaneTypes, String licence, Set<PilotLicence> pilotLicences) {
       this.airplaneTypes = airplaneTypes;
       this.licence = licence;
       this.pilotLicences = pilotLicences;
    }
   
    public Integer getIdairplaneLicence() {
        return this.idairplaneLicence;
    }
    
    public void setIdairplaneLicence(Integer idairplaneLicence) {
        this.idairplaneLicence = idairplaneLicence;
    }
    public AirplaneTypes getAirplaneTypes() {
        return this.airplaneTypes;
    }
    
    public void setAirplaneTypes(AirplaneTypes airplaneTypes) {
        this.airplaneTypes = airplaneTypes;
    }
    public String getLicence() {
        return this.licence;
    }
    
    public void setLicence(String licence) {
        this.licence = licence;
    }
    public Set<PilotLicence> getPilotLicences() {
        return this.pilotLicences;
    }
    
    public void setPilotLicences(Set<PilotLicence> pilotLicences) {
        this.pilotLicences = pilotLicences;
    }




}


