package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * AirportCord generated by hbm2java
 */
public class AirportCord  implements java.io.Serializable {


     private Integer idairportCord;
     private Airport airport;
     private double lat;
     private double lng;

    public AirportCord() {
    }

    public AirportCord(Airport airport, double lat, double lng) {
       this.airport = airport;
       this.lat = lat;
       this.lng = lng;
    }
   
    public Integer getIdairportCord() {
        return this.idairportCord;
    }
    
    public void setIdairportCord(Integer idairportCord) {
        this.idairportCord = idairportCord;
    }
    public Airport getAirport() {
        return this.airport;
    }
    
    public void setAirport(Airport airport) {
        this.airport = airport;
    }
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }
    public double getLng() {
        return this.lng;
    }
    
    public void setLng(double lng) {
        this.lng = lng;
    }




}


