package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airplane generated by hbm2java
 */
public class Airplane  implements java.io.Serializable {


     private Integer idairplane;
     private AirlineCompany airlineCompany;
     private AirplaneTypes airplaneTypes;
     private String name;
     private Set<Flight> flights = new HashSet<Flight>(0);

    public Airplane() {
    }

	
    public Airplane(AirlineCompany airlineCompany, AirplaneTypes airplaneTypes, String name) {
        this.airlineCompany = airlineCompany;
        this.airplaneTypes = airplaneTypes;
        this.name = name;
    }
    public Airplane(AirlineCompany airlineCompany, AirplaneTypes airplaneTypes, String name, Set<Flight> flights) {
       this.airlineCompany = airlineCompany;
       this.airplaneTypes = airplaneTypes;
       this.name = name;
       this.flights = flights;
    }
   
    public Integer getIdairplane() {
        return this.idairplane;
    }
    
    public void setIdairplane(Integer idairplane) {
        this.idairplane = idairplane;
    }
    public AirlineCompany getAirlineCompany() {
        return this.airlineCompany;
    }
    
    public void setAirlineCompany(AirlineCompany airlineCompany) {
        this.airlineCompany = airlineCompany;
    }
    public AirplaneTypes getAirplaneTypes() {
        return this.airplaneTypes;
    }
    
    public void setAirplaneTypes(AirplaneTypes airplaneTypes) {
        this.airplaneTypes = airplaneTypes;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Flight> getFlights() {
        return this.flights;
    }
    
    public void setFlights(Set<Flight> flights) {
        this.flights = flights;
    }




}


