package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Airport generated by hbm2java
 */
public class Airport  implements java.io.Serializable {


     private Integer idairport;
     private String name;
     private String iata;
     private String city;
     private String country;
     private int runwayNum;
     private int terminalNum;
     private Set<Flight> flightsForUnexpAirport = new HashSet<Flight>(0);
     private Set<Flight> flightsForStartAirport = new HashSet<Flight>(0);
     private Set<AirportCord> airportCords = new HashSet<AirportCord>(0);
     private Set<Flight> flightsForEndAirport = new HashSet<Flight>(0);
     private Set<Gates> gateses = new HashSet<Gates>(0);

    public Airport() {
    }

	
    public Airport(String name, String iata, String city, String country, int runwayNum, int terminalNum) {
        this.name = name;
        this.iata = iata;
        this.city = city;
        this.country = country;
        this.runwayNum = runwayNum;
        this.terminalNum = terminalNum;
    }
    public Airport(String name, String iata, String city, String country, int runwayNum, int terminalNum, Set<Flight> flightsForUnexpAirport, Set<Flight> flightsForStartAirport, Set<AirportCord> airportCords, Set<Flight> flightsForEndAirport, Set<Gates> gateses) {
       this.name = name;
       this.iata = iata;
       this.city = city;
       this.country = country;
       this.runwayNum = runwayNum;
       this.terminalNum = terminalNum;
       this.flightsForUnexpAirport = flightsForUnexpAirport;
       this.flightsForStartAirport = flightsForStartAirport;
       this.airportCords = airportCords;
       this.flightsForEndAirport = flightsForEndAirport;
       this.gateses = gateses;
    }
   
    public Integer getIdairport() {
        return this.idairport;
    }
    
    public void setIdairport(Integer idairport) {
        this.idairport = idairport;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIata() {
        return this.iata;
    }
    
    public void setIata(String iata) {
        this.iata = iata;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public int getRunwayNum() {
        return this.runwayNum;
    }
    
    public void setRunwayNum(int runwayNum) {
        this.runwayNum = runwayNum;
    }
    public int getTerminalNum() {
        return this.terminalNum;
    }
    
    public void setTerminalNum(int terminalNum) {
        this.terminalNum = terminalNum;
    }
    public Set<Flight> getFlightsForUnexpAirport() {
        return this.flightsForUnexpAirport;
    }
    
    public void setFlightsForUnexpAirport(Set<Flight> flightsForUnexpAirport) {
        this.flightsForUnexpAirport = flightsForUnexpAirport;
    }
    public Set<Flight> getFlightsForStartAirport() {
        return this.flightsForStartAirport;
    }
    
    public void setFlightsForStartAirport(Set<Flight> flightsForStartAirport) {
        this.flightsForStartAirport = flightsForStartAirport;
    }
    public Set<AirportCord> getAirportCords() {
        return this.airportCords;
    }
    
    public void setAirportCords(Set<AirportCord> airportCords) {
        this.airportCords = airportCords;
    }
    public Set<Flight> getFlightsForEndAirport() {
        return this.flightsForEndAirport;
    }
    
    public void setFlightsForEndAirport(Set<Flight> flightsForEndAirport) {
        this.flightsForEndAirport = flightsForEndAirport;
    }
    public Set<Gates> getGateses() {
        return this.gateses;
    }
    
    public void setGateses(Set<Gates> gateses) {
        this.gateses = gateses;
    }




}


