package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AirplaneTypes generated by hbm2java
 */
public class AirplaneTypes  implements java.io.Serializable {


     private Integer idairplaneTypes;
     private AirplaneMaker airplaneMaker;
     private String name;
     private String licence;
     private int passNum;
     private Set<Airplane> airplanes = new HashSet<Airplane>(0);
     private Set<AirplaneLicence> airplaneLicences = new HashSet<AirplaneLicence>(0);

    public AirplaneTypes() {
    }

	
    public AirplaneTypes(AirplaneMaker airplaneMaker, String name, String licence, int passNum) {
        this.airplaneMaker = airplaneMaker;
        this.name = name;
        this.licence = licence;
        this.passNum = passNum;
    }
    public AirplaneTypes(AirplaneMaker airplaneMaker, String name, String licence, int passNum, Set<Airplane> airplanes, Set<AirplaneLicence> airplaneLicences) {
       this.airplaneMaker = airplaneMaker;
       this.name = name;
       this.licence = licence;
       this.passNum = passNum;
       this.airplanes = airplanes;
       this.airplaneLicences = airplaneLicences;
    }
   
    public Integer getIdairplaneTypes() {
        return this.idairplaneTypes;
    }
    
    public void setIdairplaneTypes(Integer idairplaneTypes) {
        this.idairplaneTypes = idairplaneTypes;
    }
    public AirplaneMaker getAirplaneMaker() {
        return this.airplaneMaker;
    }
    
    public void setAirplaneMaker(AirplaneMaker airplaneMaker) {
        this.airplaneMaker = airplaneMaker;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLicence() {
        return this.licence;
    }
    
    public void setLicence(String licence) {
        this.licence = licence;
    }
    public int getPassNum() {
        return this.passNum;
    }
    
    public void setPassNum(int passNum) {
        this.passNum = passNum;
    }
    public Set<Airplane> getAirplanes() {
        return this.airplanes;
    }
    
    public void setAirplanes(Set<Airplane> airplanes) {
        this.airplanes = airplanes;
    }
    public Set<AirplaneLicence> getAirplaneLicences() {
        return this.airplaneLicences;
    }
    
    public void setAirplaneLicences(Set<AirplaneLicence> airplaneLicences) {
        this.airplaneLicences = airplaneLicences;
    }




}


