package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * FlightCrew generated by hbm2java
 */
public class FlightCrew  implements java.io.Serializable {


     private Integer idflightCrew;
     private Flight flight;
     private User user;
     private int job;

    public FlightCrew() {
    }

    public FlightCrew(Flight flight, User user, int job) {
       this.flight = flight;
       this.user = user;
       this.job = job;
    }
   
    public Integer getIdflightCrew() {
        return this.idflightCrew;
    }
    
    public void setIdflightCrew(Integer idflightCrew) {
        this.idflightCrew = idflightCrew;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getJob() {
        return this.job;
    }
    
    public void setJob(int job) {
        this.job = job;
    }




}


