package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * Gates generated by hbm2java
 */
public class Gates  implements java.io.Serializable {


     private Integer idgates;
     private Airport airport;
     private String terminal;
     private String gateName;

    public Gates() {
    }

    public Gates(Airport airport, String terminal, String gateName) {
       this.airport = airport;
       this.terminal = terminal;
       this.gateName = gateName;
    }
   
    public Integer getIdgates() {
        return this.idgates;
    }
    
    public void setIdgates(Integer idgates) {
        this.idgates = idgates;
    }
    public Airport getAirport() {
        return this.airport;
    }
    
    public void setAirport(Airport airport) {
        this.airport = airport;
    }
    public String getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }
    public String getGateName() {
        return this.gateName;
    }
    
    public void setGateName(String gateName) {
        this.gateName = gateName;
    }




}


