package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * MadeFinal generated by hbm2java
 */
public class MadeFinal  implements java.io.Serializable {


     private Integer idmadeFinal;
     private String name;
     private String tip;

    public MadeFinal() {
    }

    public MadeFinal(String name, String tip) {
       this.name = name;
       this.tip = tip;
    }
   
    public Integer getIdmadeFinal() {
        return this.idmadeFinal;
    }
    
    public void setIdmadeFinal(Integer idmadeFinal) {
        this.idmadeFinal = idmadeFinal;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }




}


