package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * Proba generated by hbm2java
 */
public class Proba  implements java.io.Serializable {


     private Integer idproba;
     private String name;

    public Proba() {
    }

    public Proba(String name) {
       this.name = name;
    }
   
    public Integer getIdproba() {
        return this.idproba;
    }
    
    public void setIdproba(Integer idproba) {
        this.idproba = idproba;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


