package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RadarCenter generated by hbm2java
 */
public class RadarCenter  implements java.io.Serializable {


     private Integer idradarCenter;
     private String name;
     private String city;
     private String country;
     private Set<RadarCord> radarCords = new HashSet<RadarCord>(0);
     private Set<RadarFlight> radarFlights = new HashSet<RadarFlight>(0);

    public RadarCenter() {
    }

	
    public RadarCenter(String name, String city, String country) {
        this.name = name;
        this.city = city;
        this.country = country;
    }
    public RadarCenter(String name, String city, String country, Set<RadarCord> radarCords, Set<RadarFlight> radarFlights) {
       this.name = name;
       this.city = city;
       this.country = country;
       this.radarCords = radarCords;
       this.radarFlights = radarFlights;
    }
   
    public Integer getIdradarCenter() {
        return this.idradarCenter;
    }
    
    public void setIdradarCenter(Integer idradarCenter) {
        this.idradarCenter = idradarCenter;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<RadarCord> getRadarCords() {
        return this.radarCords;
    }
    
    public void setRadarCords(Set<RadarCord> radarCords) {
        this.radarCords = radarCords;
    }
    public Set<RadarFlight> getRadarFlights() {
        return this.radarFlights;
    }
    
    public void setRadarFlights(Set<RadarFlight> radarFlights) {
        this.radarFlights = radarFlights;
    }




}


