package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * RadarFlight generated by hbm2java
 */
public class RadarFlight  implements java.io.Serializable {


     private Integer idradarFlight;
     private Flight flight;
     private RadarCenter radarCenter;

    public RadarFlight() {
    }

    public RadarFlight(Flight flight, RadarCenter radarCenter) {
       this.flight = flight;
       this.radarCenter = radarCenter;
    }
   
    public Integer getIdradarFlight() {
        return this.idradarFlight;
    }
    
    public void setIdradarFlight(Integer idradarFlight) {
        this.idradarFlight = idradarFlight;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public RadarCenter getRadarCenter() {
        return this.radarCenter;
    }
    
    public void setRadarCenter(RadarCenter radarCenter) {
        this.radarCenter = radarCenter;
    }




}


