package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegisterUser generated by hbm2java
 */
public class RegisterUser  implements java.io.Serializable {


     private Integer idregisterUser;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String email;
     private int type;
     private String airline;
     private Date birthdate;

    public RegisterUser() {
    }

    public RegisterUser(String username, String password, String firstName, String lastName, String email, int type, String airline, Date birthdate) {
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.type = type;
       this.airline = airline;
       this.birthdate = birthdate;
    }
   
    public Integer getIdregisterUser() {
        return this.idregisterUser;
    }
    
    public void setIdregisterUser(Integer idregisterUser) {
        this.idregisterUser = idregisterUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getAirline() {
        return this.airline;
    }
    
    public void setAirline(String airline) {
        this.airline = airline;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }




}


