package database;
// Generated Aug 24, 2017 3:10:22 PM by Hibernate Tools 4.3.1



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer idreservation;
     private Flight flight;
     private int passport;
     private int people;
     private int number;

    public Reservation() {
    }

    public Reservation(Flight flight, int passport, int people, int number) {
       this.flight = flight;
       this.passport = passport;
       this.people = people;
       this.number = number;
    }
   
    public Integer getIdreservation() {
        return this.idreservation;
    }
    
    public void setIdreservation(Integer idreservation) {
        this.idreservation = idreservation;
    }
    public Flight getFlight() {
        return this.flight;
    }
    
    public void setFlight(Flight flight) {
        this.flight = flight;
    }
    public int getPassport() {
        return this.passport;
    }
    
    public void setPassport(int passport) {
        this.passport = passport;
    }
    public int getPeople() {
        return this.people;
    }
    
    public void setPeople(int people) {
        this.people = people;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }




}


